"""empty message

Revision ID: ec83524bc819
Revises: b66804cc2cc3
Create Date: 2023-11-04 14:42:52.522618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ec83524bc819'
down_revision: Union[str, None] = 'b66804cc2cc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_id', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_transaction_info_currency', table_name='transaction_info')
    op.drop_index('ix_transaction_info_description', table_name='transaction_info')
    op.drop_index('ix_transaction_info_id', table_name='transaction_info')
    op.drop_index('ix_transaction_info_name', table_name='transaction_info')
    op.drop_table('transaction_info')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction_info',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('description', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('amount', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('currency', mysql.VARCHAR(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_transaction_info_name', 'transaction_info', ['name'], unique=False)
    op.create_index('ix_transaction_info_id', 'transaction_info', ['id'], unique=False)
    op.create_index('ix_transaction_info_description', 'transaction_info', ['description'], unique=False)
    op.create_index('ix_transaction_info_currency', 'transaction_info', ['currency'], unique=False)
    op.create_table('users',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=150), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=150), nullable=True),
    sa.Column('password', mysql.VARCHAR(length=150), nullable=True),
    sa.Column('full_name', mysql.VARCHAR(length=150), nullable=True),
    sa.Column('disabled', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    # ### end Alembic commands ###
